version: 0.0
os: linux
files:
    - source: /
      destination: /
hooks:
    BeforeInstall:
        - location: scripts/pre-install.sh
          timeout: 300
    AfterInstall:
        - location: scripts/post-install.sh
          timeout: 300
    ApplicationStart:
        - location: scripts/healthcare-start.sh
          timeout: 300
    ApplicationStop:
        - location: scripts/healthcare-stop.sh
          timeout: 300

